package Tugas5.view;

import Tugas5.helper.PenghitungKataHelper;
import javax.swing.JOptionPane;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author Achmad Rafiq Syaddid
 */
public class AplikasiPenghitungKata extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AplikasiPenghitungKata.class.getName());

    /**
     * Creates new form AplikasiPenghitungKata
     */
    public AplikasiPenghitungKata() {
    initComponents();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelKata = new javax.swing.JLabel();
        jLabelKarakter = new javax.swing.JLabel();
        jLabelKalimat = new javax.swing.JLabel();
        jLabelParagraf = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonHitung = new javax.swing.JButton();
        jButtonSimpan = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabelCari = new javax.swing.JLabel();
        jButtonCari = new javax.swing.JButton();
        jTampilan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Penghitung Kata");
        setBackground(new java.awt.Color(250, 250, 230));

        jPanel1.setBackground(new java.awt.Color(255, 243, 229));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HASIL PERHITUNGAN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabelKata.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelKata.setText("Jumlah Kata         :");

        jLabelKarakter.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelKarakter.setText("Jumlah Karakter  :");

        jLabelKalimat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelKalimat.setText("Jumlah Kalimat    :");

        jLabelParagraf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelParagraf.setText("Jumlah Paragraf  :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelParagraf)
                    .addComponent(jLabelKalimat)
                    .addComponent(jLabelKarakter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelKata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(410, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelKata)
                .addGap(18, 18, 18)
                .addComponent(jLabelKarakter)
                .addGap(18, 18, 18)
                .addComponent(jLabelKalimat)
                .addGap(18, 18, 18)
                .addComponent(jLabelParagraf)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTextArea1.setBackground(new java.awt.Color(0, 153, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonHitung.setBackground(new java.awt.Color(228, 228, 228));
        jButtonHitung.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonHitung.setText("Hitung");
        jButtonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHitungActionPerformed(evt);
            }
        });

        jButtonSimpan.setBackground(new java.awt.Color(226, 226, 226));
        jButtonSimpan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabelCari.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelCari.setText("Search");

        jButtonCari.setBackground(new java.awt.Color(226, 226, 226));
        jButtonCari.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonCari.setText("Cari");
        jButtonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCariActionPerformed(evt);
            }
        });

        jTampilan.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jTampilan.setText("APLIKASI PENGHITUNG KATA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTampilan, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonHitung)
                    .addComponent(jButtonSimpan))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabelCari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCari)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTampilan)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonHitung)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSimpan)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCari)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCari))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHitungActionPerformed
  String teks = jTextArea1.getText();

        int jumlahKata = PenghitungKataHelper.hitungKata(teks);
        int jumlahKarakter = PenghitungKataHelper.hitungKarakter(teks);
        int jumlahKalimat = PenghitungKataHelper.hitungKalimat(teks);
        int jumlahParagraf = PenghitungKataHelper.hitungParagraf(teks);

        jLabelKata.setText("Jumlah Kata : " + jumlahKata);
        jLabelKarakter.setText("Jumlah Karakter : " + jumlahKarakter);
        jLabelKalimat.setText("Jumlah Kalimat : " + jumlahKalimat);
        jLabelParagraf.setText("Jumlah Paragraf : " + jumlahParagraf);
    }//GEN-LAST:event_jButtonHitungActionPerformed

    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed
String teks = jTextArea1.getText();
        String kataDicari = jTextField1.getText();

        if (kataDicari.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan kata yang ingin dicari!");
            return;
        }

        int jumlah = PenghitungKataHelper.cariKata(teks, kataDicari);
        JOptionPane.showMessageDialog(this, 
                "Kata \"" + kataDicari + "\" ditemukan sebanyak " + jumlah + " kali dalam teks.");
    }//GEN-LAST:event_jButtonCariActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
 try {
            FileWriter writer = new FileWriter("hasil_penghitungan.txt");
            writer.write("=== HASIL PENGHITUNGAN TEKS ===\n\n");
            writer.write("Teks Asli:\n" + jTextArea1.getText() + "\n\n");
            writer.write(jLabelKata.getText() + "\n");
            writer.write(jLabelKarakter.getText() + "\n");
            writer.write(jLabelKalimat.getText() + "\n");
            writer.write(jLabelParagraf.getText() + "\n");
            writer.close();

            JOptionPane.showMessageDialog(this, 
                "Hasil berhasil disimpan ke file: hasil_penghitungan.txt");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, 
                "Terjadi kesalahan saat menyimpan file: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AplikasiPenghitungKata().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonHitung;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JLabel jLabelCari;
    private javax.swing.JLabel jLabelKalimat;
    private javax.swing.JLabel jLabelKarakter;
    private javax.swing.JLabel jLabelKata;
    private javax.swing.JLabel jLabelParagraf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTampilan;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
